name: CD-Update
on:
  push:
    branches: [master]
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts
